### PR TITLE
Fix/31 network indicator

### LINKED ISSUE #31: Add network connection indicator and injected extension handling
# Task Summary

We want to change the style for the network connection component and handling browser injections from extension wallets.

The client app should show a stylized spinner when initializing the application. After the application has been loaded (and connected to the chain), there should be an indicator for the API connection status.
We need a chain metadata upload feature for browser extensions to register Plasm Network chain metadata.

# Task List

- [x] change the initial network connection spinner style to be an overlay of the main page instead of a white blank page when opening the page for the first time https://github.com/PlasmNetwork/plasm-apps-vue/blob/9d0538083fe77423370fdec5351de34e010047c4/src/App.vue#L11 https://github.com/PlasmNetwork/plasm-apps-vue/blob/9d0538083fe77423370fdec5351de34e010047c4/src/components/common/ModalLoading.vue#L7

- [x] add network connection status indicator (a colored dot) to the side of the main logo in the sidebar. Green for connected, pulsing orange for connecting, red when the client is offline https://github.com/PlasmNetwork/plasm-apps-vue/blob/c99b29f290bf2b3be6dd96a886fb112a0aa52a19/src/components/common/SidebarCommon.vue#L3
add-connection-status

- [ ] show a popup that asks the user to install polkadot-js extension if no account was loaded from the client ([firefox](https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-extension/), [chrome](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd)) https://github.com/PlasmNetwork/plasm-apps-vue/blob/9723ad6386e0a6d1d170b5ac4490424c41cea4b4/src/api/polkadot/connectApi.ts#L24
show-popup-when-no-account

### PR DESCRIPTION
**Pull request by sirius651**
# Pull Request Summary

Fixed #31 

including rebranding

except this task : `if there the chain is sending new metadata for the client's extension, display an extension metadata update button `

### CODE REVIEW

**Comment by sirius651** [comment]
Regarding this task ` if there the chain is sending new metadata for the client's extension, display an extension metadata update button ` , because it seems complicated, so it should be one of big task what I'll be in charged of. so, is it okay go ahead to #33 at first, then take in later? @hoonsubin

**Comment by hoonsubin** [comment]
you're right. I'll open a new issue regarding the extension metadata update!

File: src/App.vue [hunk 1]
```diff
@@ -1,21 +1,30 @@
 <template>
   <metainfo>
     <template v-slot:title="{ content }">{{
-      content ? `${content} | Plasm Apps Portal` : `Plasm Apps Portal`
+      content ? `${content} | Astar Apps Portal` : `Astar Apps Portal`
```
Comment (hoonsubin) [inline src/App.vue:4]: When first loading the app, the default page title will be shown as `<title><%= htmlWebpackPlugin.options.title %></title>` which is `plasm-apps-vue`. Can you fix this so that we can set a default page metadata. For example, we can configure it so that the title will say `Astar Apps Portal` as the page title when it is still connecting to the chain.

Similarly, I think it's good to use the default network favicon for the local network as well.
bandicam 2021-06-28 16-03-47-835

**Review by hoonsubin — CHANGES_REQUESTED** [review]
including the other change requests, can you use this icon for the main net favicon?

astar-favicon

File: src/views/Balance.vue [hunk 2]
```diff
@@ -9,7 +9,7 @@
     </h1>
     <Tab
       :labels="[
-        { label: 'Plasm', path: 'balance-plasm' },
+        { label: 'Astar', path: 'balance-plasm' },
```
Comment (hoonsubin) [inline src/views/Balance.vue:12]: Instead of `Astar`, can you name the tab as `Wallet`?

**Review by hoonsubin — CHANGES_REQUESTED** [review]

File: src/views/Balance.vue (hunk 2 above)
Comment (hoonsubin) [inline src/views/Balance.vue]: Instead of `Astar`, can you name the tab as `Wallet`?

**Review by hoonsubin — CHANGES_REQUESTED** [review]

**Comment by hoonsubin** [comment]
@sirius651 This is not directly related to the scope of this pull request, but I recommend using the `@apply` style directives in TailwindCSS for easier class grouping https://tailwindcss.com/docs/functions-and-directives#apply for this pattern https://github.com/PlasmNetwork/plasm-apps-vue/blob/c99b29f290bf2b3be6dd96a886fb112a0aa52a19/src/components/balance/ModalNetwork.vue#L156-L163

**Review by hoonsubin — APPROVED** [review]
LGTM
